### ISSUE TITLE
Clean Up Task: Technical debt clean up

### ISSUE THREAD

**Issue by LHMoritz** [amosproj/amos2024ws02-backup-metadata-analyzer#92]
## User story
1. As a software developer
2. I need the following things to get fixed
3. So that I can continue implementing features without running into existing problems.

## Acceptance criteria
* Criterion 1: All TODOs are analysed and actions are taken

## TODOs:

- [x] Switch to decimal numbers (frontend, backend, analyzer) (have noticed there are also some backups < 1 MB)
- [x] Check for duplicate alarms in the backend
- [x] alarmLimit should be optional QueryParam according to REST style
- [x] We need an env variable in the backend to activate/deactivate the mailing, otherwise it's super annoying
- [x] Actually, the analyzer should only check new backups that have not yet been checked, but how do we do that?
- [x] Do not only import FULL backups, so that alerts can also be linked to them. But do not deliver them to the frontend

**Comment by flo0852** [comment]
AlertType Table saves date of last backup which was checked by this type analysis + provide Endpoint to call for analyzer
